name: comanda_full
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_slidable: ^3.0.0
  dio: ^5.3.3
  flutter_web_browser: ^0.14.0
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.0
  image_picker: ^1.0.4
  another_flutter_splash_screen: ^1.2.0
  http: ^1.1.0
  pdf: ^3.10.6
  path_provider: ^2.1.1
  flutter_pdfview: ^1.3.1
  share_extend: ^2.0.0
  syncfusion_flutter_pdfviewer: ^23.1.39
  flutter_full_pdf_viewer_null_safe: ^1.0.0
  vibration: ^1.8.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

  flutter_lints: ^2.0.0
  cached_network_image: ^3.3.1
  flutter_colorpicker: ^1.0.3

flutter:

  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: TrainOne
      fonts:
        - asset: assets/fonts/TrainOne-Regular.ttf
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Black.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
        - asset: assets/fonts/Orbitron-ExtraBold.ttf
        - asset: assets/fonts/Orbitron-Medium.ttf
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-SemiBold.ttf
        - asset: assets/fonts/Orbitron-VariableFont_wght.ttf



  assets:
    - assets/images/